version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    restart: always
    volumes:
     - ./nginx/certs/:/etc/nginx/certs/
     - ./nginx/conf.d/:/etc/nginx/conf.d/
     - ./nginx/logs/:/var/log/nginx/
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_PORT=80
     - TZ=Asia/Shanghai
    networks:
      - aion
    depends_on:
      - php
  php:
    build: .
    container_name: "php"
    volumes:
     - /data/www/github.com/glauca/aion-api/:/var/www/html/aion-api/
    networks:
      - aion
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Asia/Shanghai
    networks:
      - aion
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis/data/:/data/
    ports:
      - 6379:6379
    networks:
      - aion
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    restart: always
    hostname: rabbit
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/conf/:/etc/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - aion
networks:
  aion:
    driver: overlay
    attachable: true
