version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    restart: always
    volumes:
     - ${PWD}/nginx/conf.d/:/etc/nginx/conf.d/
     - ${PWD}/nginx/logs/:/vat/log/nginx/
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_PORT=80
     - TZ=Asia/Shanghai
    networks:
      - aion
    depends_on:
      - php
  php:
    build: .
    container_name: "php"
    volumes:
     - ~/www/repo/github.com/glauca/aion-api/:/www/
    networks:
      - aion
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ${PWD}/mysql/data/:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    networks:
      - aion
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ${PWD}/redis/data/:/data/
    ports:
      - 6379:6379
    networks:
      - aion
networks:
  aion:
    driver: overlay
    attachable: true
